services:
  backend:
    image: ghcr.io/jrostek/flashcards-backend:main
    build:
      context: ./backend
      dockerfile: FlashCards.Api/Dockerfile
    environment:
      DB_PASSWORD: ${Sa_Password}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: replicated
      replicas: 2
